"""
TikTok msToken auto-refresher.

Opens a fresh Playwright browser every REFRESH_INTERVAL minutes,
visits tiktok.com, extracts the msToken cookie, and appends it to
tokens.txt. The scraper reads tokens.txt periodically to pick up
new tokens without restart.

Run in a separate terminal:
    python token_refresher.py

Stop with Ctrl+C. State is just tokens.txt — safe to restart any time.
"""
import asyncio
import logging
import os
import sys
import time
from pathlib import Path

from dotenv import load_dotenv

try:
    from playwright.async_api import async_playwright
except ImportError:
    print("Playwright not installed. Run: pip install playwright && python -m playwright install chromium")
    sys.exit(1)

load_dotenv()

REFRESH_INTERVAL_MIN = int(os.getenv("TOKEN_REFRESH_INTERVAL_MIN", "30"))
TOKENS_FILE = Path(__file__).parent / "tokens.txt"
LOG_PATH = Path(__file__).parent / "token_refresher.log"
MAX_TOKENS = 50    # keep most recent N tokens in tokens.txt

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(LOG_PATH, encoding="utf-8"),
        logging.StreamHandler(sys.stdout),
    ],
)
log = logging.getLogger("refresher")


async def grab_token(timeout_sec: int = 60) -> str | None:
    """Open Chromium, visit tiktok.com, extract msToken cookie. Returns token or None."""
    async with async_playwright() as p:
        browser = await p.chromium.launch(
            headless=True,
            args=[
                "--disable-blink-features=AutomationControlled",
                "--disable-features=IsolateOrigins,site-per-process",
            ],
        )
        try:
            context = await browser.new_context(
                user_agent=(
                    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) "
                    "Chrome/124.0.0.0 Safari/537.36"
                ),
                locale="en-US",
                viewport={"width": 1280, "height": 800},
            )
            page = await context.new_page()
            try:
                await page.goto("https://www.tiktok.com/", timeout=timeout_sec * 1000, wait_until="domcontentloaded")
            except Exception as e:
                log.warning(f"Initial navigation failed: {e}")
            # Wait a few seconds for cookies to be set
            await asyncio.sleep(8)

            cookies = await context.cookies("https://www.tiktok.com")
            for c in cookies:
                if c.get("name") == "msToken":
                    val = c.get("value", "").strip()
                    if val and len(val) > 50:
                        return val
            return None
        finally:
            await browser.close()


def read_existing_tokens() -> list[str]:
    if not TOKENS_FILE.exists():
        return []
    return [
        line.strip()
        for line in TOKENS_FILE.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


def save_tokens(tokens: list[str]):
    """Keep only the most recent MAX_TOKENS, write to file atomically."""
    keep = tokens[-MAX_TOKENS:]
    body = "# Auto-generated by token_refresher.py — most recent first\n"
    body += "# Scraper auto-reads this file. Safe to edit by hand if needed.\n"
    for t in reversed(keep):
        body += t + "\n"
    tmp = TOKENS_FILE.with_suffix(".tmp")
    tmp.write_text(body, encoding="utf-8")
    tmp.replace(TOKENS_FILE)


async def main():
    log.info(f"Token refresher started. Interval: {REFRESH_INTERVAL_MIN} min. File: {TOKENS_FILE}")

    # Initial grab
    while True:
        try:
            existing = read_existing_tokens()
            log.info(f"Currently {len(existing)} token(s) in {TOKENS_FILE.name}")

            log.info("Opening Chromium to grab fresh msToken…")
            t0 = time.time()
            token = await grab_token()
            dur = time.time() - t0

            if token:
                if token in existing:
                    log.info(f"Token {token[:16]}… already in file (took {dur:.1f}s) — skipping")
                else:
                    existing.append(token)
                    save_tokens(existing)
                    log.warning(
                        f"✓ NEW TOKEN added: {token[:16]}… ({len(token)} chars, took {dur:.1f}s). "
                        f"Total tokens: {min(len(existing), MAX_TOKENS)}"
                    )
            else:
                log.warning(f"Could not extract msToken (took {dur:.1f}s). Will retry next cycle.")
        except Exception as e:
            log.error(f"Refresh failed: {e}")

        # Sleep until next interval
        sleep_sec = REFRESH_INTERVAL_MIN * 60
        log.info(f"Sleeping {REFRESH_INTERVAL_MIN} min until next refresh…")
        await asyncio.sleep(sleep_sec)


if __name__ == "__main__":
    if sys.platform == "win32":
        asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\nToken refresher stopped.")
